version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  app-backend:
    container_name: app-backend
    depends_on:
      - mysqldb
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - PORT=$NODE_LOCAL_PORT
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend
    

volumes: 
  db:

networks:
  backend:
  frontend: